<a href="https://colab.research.google.com/github/NileshPatil24-a/Complete_DataScience_Revision/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [ ]:
# series
label = ['a','b','c']
numer = [10,20,30]
arr = np.array([12,3,4,5])
dict = {'a':3, 'e':4, 2:4}

pd.Series(label, name='char')

0    a
1    b
2    c
Name: age, dtype: object

In [ ]:
pd.Series(dict, name='numbers')

a    3
e    4
2    4
Name: numbers, dtype: int64

In [4]:
df = pd.DataFrame({
    "A":[1,2,3,4,5,6],
    "B":[10,20,30,40,50,60],
    "C":[100,200,300,400,500,600]
})

In [5]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
5  6  60  600

In [6]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int64
 1   B       6 non-null      int64
 2   C       6 non-null      int64
dtypes: int64(3)
memory usage: 276.0 bytes

In [8]:
df.describe()

              A          B           C
count  6.000000   6.000000    6.000000
mean   3.500000  35.000000  350.000000
std    1.870829  18.708287  187.082869
min    1.000000  10.000000  100.000000
25%    2.250000  22.500000  225.000000
50%    3.500000  35.000000  350.000000
75%    4.750000  47.500000  475.000000
max    6.000000  60.000000  600.000000

In [11]:
def square(x):
  return x**2

In [13]:
df["A"] = df["A"].apply(square)

In [15]:
df["B"] = df["B"].apply(lambda x : x**2)

In [42]:
df = pd.read_csv("https://raw.githubusercontent.com/AkarshVyas/Pandas-Youtube/refs/heads/main/anime.csv")

In [43]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [44]:
def episode(string ):
  return string.split("(")[1][0:3].strip()

In [45]:
df["episode"] = df["Title"].apply(episode)

In [46]:
def replace_e(txt):
  return int(txt.replace("e", ""))

In [48]:
df["episode"] = df["episode"].apply(replace_e)

In [49]:
df.head()

   Rank                                              Title  Score  episode
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [67]:
df["time_stamp"] =  df["Title"].apply(lambda txt : txt.split(")")[1][:19])

In [68]:
df.head()

,Rank,Title,Score,episode,time_stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [69]:
df = pd.read_csv("https://raw.githubusercontent.com/AkarshVyas/Pandas-Youtube/refs/heads/main/Countries.csv")

In [70]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [71]:
df.values

array([['Afghanistan', 'Islamic State of Afghanistan', 'Afghan afghani',
        ..., 12.9, 'Ashraf Ghani', 'President'],
       ['Albania', 'Republic of Albania', 'Albanian lek', ..., 33.7,
        'Edi Rama', 'Prime Minister'],
       ['Algeria', "People's Democratic Republic of Algeria",
        'Algerian dinar', ..., 24.0, 'Abdelmadjid Tebboune', 'President'],
       ...,
       ['Yemen', 'Republic of Yemen', 'Yemeni rial', ..., 14.8,
        'Abdrabbuh Mansur Hadi', 'President'],
       ['Zambia', 'Republic of Zambia', 'New Zambian kwacha', ..., 13.2,
        'Edgar Lungu', 'President'],
       ['Zimbabwe', 'Republic of Zimbabwe', 'U.S. dollar', ..., 14.2,
        'Emmerson Mnangagwa', 'President']], dtype=object)

In [72]:
df.rename(columns={"country":"Country"})

,Country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President